spring:
  jpa:
    # ?? ?? ?, table ?? create ??? ??
    database: mysql
    hibernate:
      ddl-auto: create
    #      ddl-auto: none
    # sql ?? log
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
        use_sql_comments: true