spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oauthtest?useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 'auddhr4494'
    driverClassName: com.mysql.cj.jdbc.Driver